### ISSUE TITLE
Eklenebilecek Kaynaklar

### ISSUE THREAD

**Issue by coderserdar** [ezgiturali/Machine-Learning-Deep-Learning-Resources#2]
Merhabalar hocam. 
Öncelikle yayınladığınız repo için teşekkür etmek istedim.
https://github.com/coderserdar/Documents
https://github.com/coderserdar/TurkceKaynaklar 
repo adreslerinde ellime geçen ingilizce ve türkçe kaynakları paylaşıyorum.
Burada makina öğrenmesi, mülakatlar vb. konularla ilgili kaynaklar var.
İsterseniz link olarak da ekleyebilirsiniz bunu kaynaklar kısmına.
Şimdiden anlayışınız için teşekkür eder, iyi günler dilerim

**Comment by ebrutasci1** [comment]
Sayın serdar GÜL
Hayırlı kandiller dilerim
Sanırım mailiniz yanlış geldi ben repo yayınlamadım bilginize 😊

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________
From: Serdar GÜL ***@***.***>
Sent: Friday, February 17, 2023 12:46:35 PM
To: ezgiturali/Machine-Learning-Deep-Learning-Resources ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ezgiturali/Machine-Learning-Deep-Learning-Resources] Eklenebilecek Kaynaklar (Issue #2)


Merhabalar hocam.
Öncelikle yayınladığınız repo için teşekkür etmek istedim.
https://github.com/coderserdar/Documents
https://github.com/coderserdar/TurkceKaynaklar
repo adreslerinde ellime geçen ingilizce ve türkçe kaynakları paylaşıyorum.
Burada makina öğrenmesi ile de kaynaklar var.
İsterseniz link olarak da ekleyebilirsiniz bunu kaynaklar kısmına.
Şimdiden anlayışınız için teşekkür eder, iyi günler dilerim

**Comment by coderserdar** [comment]
Merhabalar Ebru hanım.
ezgi turalı'nın reposuna bir issue açmıştım.
Size nasıl mail geldi ben de anlamadım

**Comment by ezgiturali** [comment]
Merhaba Serdar,
Çok güzel ve detaylı bir repo olmuş eline sağlık. Useful Repos diye bir başlık açıp ekledim, teşekkür ederim.
İyi çalışmalar.

**Comment by coderserdar** [comment]
Rica ederim. Katkımız olduysa ne mutlu bize.
İyi günler, iyi çalışmalar
